name: Container
on: push

jobs:
  update-type-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 1286086cc3b0f81c85f4bed9b9d00f81
          filename: test_badge.json
          typeCoverage: 14.50
