name: Container
on: push

jobs:
  update-type-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate Type Coverage 
        run: |
          TYPE_COV_RES=$(npx type-coverage | head -1)
          echo $TYPE_COV_RES
          echo "action_state=$( $TYPE_COV_RES )" >> $GITHUB_ENV

          # echo "text<<EOF" >> $GITHUB_ENV
          # TYPE_COV_RES=$(npx type-coverage)
          # echo "action_state=$TYPE_COV_RES" >> $GITHUB_ENV
          # echo "EOF" >> $GITHUB_ENV

          # echo "action_state=$( echo hello )" >> $GITHUB_ENV
          # echo "::set-output name=NODE_VERSION::$(
          #   npx type-coverage
          # )"
        id: coverageResult
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 1286086cc3b0f81c85f4bed9b9d00f81
          filename: test_badge.json
          label: type-coverage
          message: ${{ env.action_state }}